version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cutemiya
      POSTGRES_DB: cutemiyadb
      POSTGRES_PASSWORD: password
    volumes:
      - ~/volumes/ctemiyadb:/var/lib/postgresql/data